### ISSUE TITLE
Issues Executing

### ISSUE THREAD

**Issue by brookesrook** [tbressler/waterrower-core#26]
I get the following when trying to run this build. Do I need to run an older version of gradle? 

> Task :test FAILED

* What went wrong:
Execution failed for task ':test'.
> There were failing tests. See the report at: file:///waterrower-core-1.2.0/build/reports/tests/test/index.html

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.8/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD FAILED in 2s
5 actionable tasks: 1 executed, 4 up-to-date

**Comment by tbressler** [comment]
Thanks for pointing this out.
I updated the dependent libraries in the project to the latest versions and did a fix to the build configuration.
I hope this works now.
