### ISSUE TITLE
Reference interpretation for Pulse

### ISSUE THREAD

**Issue by vojkny** [tbressler/waterrower-core#3]
Hi,

could you provide a reference how to interpret the pulse counts – I guess this should be used to obtain distance?

**Comment by tbressler** [comment]
The documentation of the WaterRower interface is quite unspecific about the pulse count event. As far as I know it is about strokes (how many strokes in a time frame occured). But I‘m very unsure about that specific event.

**Comment by vojkny** [comment]
And how do you interpret these within your code?

I actually found out, that the count of pulses roughly corresponds to the distance - or at least on my trainer: `distanceInMeters = pulses * 1.1 / 100`

**Comment by tbressler** [comment]
After some final tests I think I found out what the pulse count stands for:

When the paddle is moving the "measuring device" of the WaterRower receives pulses from the rotary movement of the paddle. With the help of the pulses received in a certain amount of time (the last 25ms) the Performance Monitor can calculate the values for distance (as @knyttl mentioned above), velocity and so on.

Thus the pulse count is a more advanced event. You can use it for your own calculations. But I would rather use the default subscriptions and values of the Performance Monitor.
